#!/usr/bin/env bash
# scripts/check-secrets-vs-types.sh
#
# CI guard for FOLLOWUP-015: verify that every secret read at runtime
# (`env.<NAME>` in workers/*.ts) has a corresponding declaration on
# `Env` in workers/types.ts. Mismatches indicate either:
#
#   - A secret is read at runtime but not declared on `Env` → callers
#     will get `undefined` at runtime even if the secret is set. The
#     CF type definitions are regenerated by `wrangler types`, but only
#     after the secret has been provisioned at least once. This guard
#     catches the case where we forgot to add the declaration.
#
#   - A secret is declared on `Env` but never read in code → leftover
#     type pollution; either delete it from types.ts or add the
#     corresponding `wrangler secret put` mention.
#
# The script greps for the patterns:
#   env\.<NAME>          — runtime reads
#   <NAME>\?: string     — declaration in types.ts
#
# Output: zero mismatches → exit 0. Any mismatch → exit 1 with a list.
#
# Usage:
#   bash scripts/check-secrets-vs-types.sh                # scan workers/
#   bash scripts/check-secrets-vs-types.sh path/to/dir    # scan custom dir

set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="${1:-$ROOT/workers}"
TYPES_FILE="${TYPES_FILE:-$ROOT/workers/types.ts}"

if [ ! -d "$TARGET" ]; then
  echo "check-secrets-vs-types: target $TARGET is not a directory" >&2
  exit 2
fi
if [ ! -f "$TYPES_FILE" ]; then
  echo "check-secrets-vs-types: types file $TYPES_FILE not found" >&2
  exit 2
fi

# Build a list of secret-like names declared on Env (optional `?: string`).
# We accept either `?: string` (declared but maybe missing) or `: string`
# (declared and required). The doc-comment is ignored.
DECLARED=$(grep -E '^[[:space:]]+[A-Z][A-Z0-9_]+\??:[[:space:]]*string' "$TYPES_FILE" \
  | sed -E 's/^[[:space:]]+([A-Z][A-Z0-9_]+).*/\1/' \
  | sort -u)

# Build a list of secret-like names READ in code via env.<NAME>.
# We don't try to be exhaustive — the goal is to catch obvious omissions,
# not prove equivalence.
READ=$(grep -rEho '\benv\.[A-Z][A-Z0-9_]+' "$TARGET" \
  --include='*.ts' --include='*.tsx' --include='*.js' \
  | sed -E 's/^env\.//' \
  | sort -u)

# Identify mismatches in both directions.
UNREAD=$(comm -23 <(echo "$DECLARED") <(echo "$READ"))
UNDEFINED=$(comm -13 <(echo "$DECLARED") <(echo "$READ"))

# Filter: only flag names that look secret-like (contain KEY, SECRET, or
# TOKEN). This avoids noise from non-secret Env vars like POLICY_AUD.
filter_secrets() {
  while IFS= read -r name; do
    case "$name" in
      *KEY*|*SECRET*|*TOKEN*) echo "$name" ;;
    esac
  done
}

PROBLEMS=0

UNREAD_SECRETS=$(echo "$UNREAD" | filter_secrets)
if [ -n "$UNREAD_SECRETS" ]; then
  echo "Declared secrets never read at runtime (remove or wire them up):" >&2
  while IFS= read -r name; do
    echo "  - $name" >&2
    PROBLEMS=$((PROBLEMS + 1))
  done <<< "$UNREAD_SECRETS"
fi

UNDEFINED_SECRETS=$(echo "$UNDEFINED" | filter_secrets)
if [ -n "$UNDEFINED_SECRETS" ]; then
  echo "Secrets read at runtime but not declared on Env (add to types.ts):" >&2
  while IFS= read -r name; do
    echo "  - $name" >&2
    PROBLEMS=$((PROBLEMS + 1))
  done <<< "$UNDEFINED_SECRETS"
fi

if [ "$PROBLEMS" -gt 0 ]; then
  echo "" >&2
  echo "Found $PROBLEMS secret mismatch(es). See above." >&2
  exit 1
fi

echo "check-secrets-vs-types: clean"
exit 0
